### ISSUE TITLE
can't get this to work.....

### ISSUE THREAD

**Issue by starchild** [CodyHouse/cd-toast-changelog#1]
Hi,

Sorry to bother you, but no matter what I can't get this to work.  Even if I strip it right back to just the demo content, it still won't work.  See https://codepen.io/george-costanza/pen/yLozXZa

Can you tell me what I'm missing please?

**Comment by starchild** [comment]
Any thoughts please?

**Comment by claudia-romano** [comment]
Hi there, please make sure you are using the `openToast` event to open your toast element, as explained in the component Info page:
https://codyhouse.co/ds/components/info/toast

**Comment by starchild** [comment]
Thank you.
