### ISSUE TITLE
Position issue after generating style with npm run gulp dist 

### ISSUE THREAD

**Issue by dariopetraroia** [CodyHouse/cd-toast-changelog#2]
Hy i have a position issue with the centered toast version when i compile the scss using npm run gulp dist

The toast in not centered well.
This css part seems to be missing:

[class*=" -rotate"], [class*=" -scale"], [class*=" -skew"] [class^=skew], [class*=" -translate"], [class*=" flip"], [class*=" rotate"], [class*=" scale"], [class*=" skew"], [class*=" translate"], [class^=-rotate], [class^=-scale], [class^=-skew], [class^=-translate], [class^=flip], [class^=rotate], [class^=scale], [class^=translate] {
    --translate: 0;
    --rotate: 0;
    --skew: 0;
    --scale: 1;
    transform: translate3d(var(--translate-x,var(--translate)),var(--translate-y,var(--translate)),var(--translate-z,0)) rotateX(var(--rotate-x,0)) rotateY(var(--rotate-y,0)) rotateZ(var(--rotate-z,var(--rotate))) skewX(var(--skew-x,var(--skew))) skewY(var(--skew-y,0)) scaleX(var(--scale-x,var(--scale))) scaleY(var(--scale-y,var(--scale)));
}

thank you

**Comment by claudia-romano** [comment]
Hi Dario, what config options are you using for purgeCSS? Thanks!

**Comment by dariopetraroia** [comment]
Hy Claudia, this is my purgeCSS function, thank you

```
function purgeCSS() {
    return new Promise(function (resolve, reject) {
        var stream = gulp.src(cssFolder + '/style.min.css')
            .pipe(purgecss({
                content: ['**/**/*.htm', scriptsJsPath + '/scripts.js'],
                safelist: ['.is-hidden', '.is-visible'],
                defaultExtractor: content => content.match(/[\w-/:%@]+(?<!:)/g) || []
            }))
            .pipe(gulp.dest(distFolder + '/css'));

        stream.on('finish', function () {
            resolve();
        });
    });
};
```

**Comment by claudia-romano** [comment]
Hi Dario, you can try with this config:
```
purgecss({
      content: ['**/**/*.html', scriptsJsPath+'/scripts.js'],
      safelist: {
        standard: ['.is-hidden', '.is-visible'],
        deep: [/class$/],
        greedy: []
      },
      defaultExtractor: content => content.match(/[\w-/:%@]+(?<!:)/g) || []
    });
```
This is the new default one we use in the framework. Let me know if this fixes your issue.

**Comment by dariopetraroia** [comment]
Hy Claudia, it works! Thank You
